# Welcome to Jekyll!
#

# Site settings
title: কারিকরি কারখানা
description: An Art and Artisan Farm
owner: Partho Protim Saha
first_published: 2016
email: sahaprotim@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://karikorikarkhana.github.io" # the base hostname & protocol for your site
social:
#  twitter: https://twitter.com/<username>
#  github: https://github.com/<username>
#  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/Karkhana.Events
#  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
